### PR TITLE
bumped base image and dependency versions

### PR DESCRIPTION
**Pull request by robertschubert**

### CODE REVIEW

**Comment by jdsika** [comment]
@robertschubert have a look at https://github.com/ASCS-eV/smart-contracts/tree/main/contracts/marketplace
To see how to implement "events" which can very easy be indexed with taquito

**Comment by robertschubert** [comment]
> @robertschubert have a look at https://github.com/ASCS-eV/smart-contracts/tree/main/contracts/marketplace To see how to implement "events" which can very easy be indexed with taquito

@jdsika for me it seems that @uZhW8Rgl from TUB already uses taquito for getting events. Or did you wanna point me to something else?

**Comment by jdsika** [comment]
> > @robertschubert have a look at https://github.com/ASCS-eV/smart-contracts/tree/main/contracts/marketplace To see how to implement "events" which can very easy be indexed with taquito
> 
> @jdsika for me it seems that @uZhW8Rgl from TUB already uses taquito for getting events. Or did you wanna point me to something else?

No, all good then. I wasn't checking your code just remembered that Markus once in a time complained about DipDup being slow.

**Review by JulianLegler — APPROVED** [review]
lgtm

**Comment by robertschubert** [comment]
thanks, merge.

**Pull request merged**
