### PR TITLE
Fixes, Refactorings, Documentation

### PR DESCRIPTION
**Pull request by robertschubert**
- changed access-token handling because they expire after 15 minutes --> added refreshing mechanism
- fixed some minor linting errors
- refactored and extracted catalog logic into a new component catalogue.js
- moved Console class to index.js so it can be referenced from there in the other modules.
- changed date format in logger
- added some debug logs.

Hope this is ok for you. If you have any doubts come back to me.
Tested it successfully in my setup.

Hint: makes https://github.com/uZhW8Rgl/EDC-Blockchain-Listener/pull/4 obsolete

### CODE REVIEW

**Comment by uZhW8Rgl** [comment]
Hi @robertschubert,

I get an 409 Error after sending the VerifiablePresentation. Is it some issue with the FC?

```
[nodemon] restarting due to changes...
[nodemon] starting `node index.js`
[INFO] [30.7.2024, 13:11:01] Server listening on port 3005.
[INFO] [30.7.2024, 13:11:01] Access token refreshed.
[INFO] [30.7.2024, 13:12:24] Change on monitored contract detected! Please visit: https://better-call.dev/ghostnet/KT1QDheV2TkL3mitzYNKzunWYhSe6MmEPTh5/tokens
[INFO] [30.7.2024, 13:12:24] Token int position: 388
[INFO] [30.7.2024, 13:12:25] Webhook received:
[INFO] [30.7.2024, 13:12:25] Status: 200
[INFO] [30.7.2024, 13:12:25] Body: OK
[INFO] [30.7.2024, 13:12:25] No metadata found
[INFO] [30.7.2024, 13:12:25] Execution time: 0.719 seconds
[INFO] [30.7.2024, 13:12:25] 1 tokens were returned
[INFO] [30.7.2024, 13:13:25] Metadata for "verifiablePresentation" found. Recursion count: 2
[INFO] [30.7.2024, 13:13:25] Status of FC response: 409
[ERROR] [30.7.2024, 13:13:25] AxiosError: Request failed with status code 409
[INFO] [30.7.2024, 13:14:31] Change on monitored contract detected! Please visit: https://better-call.dev/ghostnet/KT1QDheV2TkL3mitzYNKzunWYhSe6MmEPTh5/tokens
[INFO] [30.7.2024, 13:14:31] Token int position: 389
[INFO] [30.7.2024, 13:14:31] Webhook received:
[INFO] [30.7.2024, 13:14:31] Status: 200
[INFO] [30.7.2024, 13:14:31] Body: OK
[INFO] [30.7.2024, 13:14:31] No metadata found
[INFO] [30.7.2024, 13:14:31] Execution time: 0.071 seconds
[INFO] [30.7.2024, 13:14:31] 1 tokens were returned
[INFO] [30.7.2024, 13:15:31] Metadata for "verifiablePresentation" found. Recursion count: 2
[INFO] [30.7.2024, 13:15:32] Status of FC response: 409
[ERROR] [30.7.2024, 13:15:32] AxiosError: Request failed with status code 409
```

**Comment by robertschubert** [comment]
Hi @uZhW8Rgl 
the message I can see in the federated catalogue is:
```
handleConflictException; Conflict error: self-description with hash 25d486aaf3de27d2859e4bbb6fd1497e2143a9c053eaa96cd3e12ec06636486a already exists
```
This happens if the VP to be stored already exists in the catalogue. 
Is that possible in your test case? Are you reusing the VPs?

**Comment by uZhW8Rgl** [comment]
Ok, yes it is posslibe if sombody is running a listener too and mine is not the first to publish. Asside from this all was working, so I will approve the changes.

**Review by uZhW8Rgl — APPROVED** [review]
All fine.

**Pull request merged**
